package com.pudutech.peanut.robot_ui.ttsvoices;

import com.aliyun.alink.linksdk.tmp.utils.TmpConstant;
import com.pudutech.peanut.robot_ui.C5508R;
import com.pudutech.peanut.robot_ui.RobotContext;
import com.pudutech.peanut.robot_ui.ttsvoices.bean.TtsVoiceItem;
import java.util.ArrayList;
import kotlin.Metadata;
import kotlin.collections.CollectionsKt;
import kotlin.jvm.internal.Intrinsics;

/* compiled from: TtsListData.kt */
@Metadata(m3959bv = {1, 0, 3}, m3960d1 = {"\u0000\u001a\n\u0002\u0018\u0002\n\u0002\u0010\u0000\n\u0002\b\u0002\n\u0002\u0018\u0002\n\u0002\u0018\u0002\n\u0002\u0018\u0002\n\u0000\u0018\u00002\u00020\u0001B\u0005¢\u0006\u0002\u0010\u0002J\u0016\u0010\u0003\u001a\u0012\u0012\u0004\u0012\u00020\u00050\u0004j\b\u0012\u0004\u0012\u00020\u0005`\u0006¨\u0006\u0007"}, m3961d2 = {"Lcom/pudutech/peanut/robot_ui/ttsvoices/TtsListData;", "", "()V", TmpConstant.PROPERTY_IDENTIFIER_GET, "Ljava/util/ArrayList;", "Lcom/pudutech/peanut/robot_ui/ttsvoices/bean/TtsVoiceItem;", "Lkotlin/collections/ArrayList;", "robot_ui_peanutRelease"}, m3962k = 1, m3963mv = {1, 1, 16})
/* loaded from: classes5.dex */
public final class TtsListData {
    public final ArrayList<TtsVoiceItem> get() {
        String name = VoiceItem.voice1_1.name();
        String string = RobotContext.INSTANCE.getContext().getString(C5508R.string.voice1_1);
        Intrinsics.checkExpressionValueIsNotNull(string, "RobotContext.context.getString(R.string.voice1_1)");
        String name2 = VoiceItem.voice5_1.name();
        String string2 = RobotContext.INSTANCE.getContext().getString(C5508R.string.voice5_1);
        Intrinsics.checkExpressionValueIsNotNull(string2, "RobotContext.context.getString(R.string.voice5_1)");
        String name3 = VoiceItem.voice5_2.name();
        String string3 = RobotContext.INSTANCE.getContext().getString(C5508R.string.voice5_2);
        Intrinsics.checkExpressionValueIsNotNull(string3, "RobotContext.context.getString(R.string.voice5_2)");
        String name4 = VoiceItem.voice6_1.name();
        String string4 = RobotContext.INSTANCE.getContext().getString(C5508R.string.voice6_1);
        Intrinsics.checkExpressionValueIsNotNull(string4, "RobotContext.context.getString(R.string.voice6_1)");
        String name5 = VoiceItem.voice7_1.name();
        String string5 = RobotContext.INSTANCE.getContext().getString(C5508R.string.voice7_1);
        Intrinsics.checkExpressionValueIsNotNull(string5, "RobotContext.context.getString(R.string.voice7_1)");
        String name6 = VoiceItem.voice8_4.name();
        String string6 = RobotContext.INSTANCE.getContext().getString(C5508R.string.voice8_4);
        Intrinsics.checkExpressionValueIsNotNull(string6, "RobotContext.context.getString(R.string.voice8_4)");
        String name7 = VoiceItem.voice9_1.name();
        String string7 = RobotContext.INSTANCE.getContext().getString(C5508R.string.voice9_1);
        Intrinsics.checkExpressionValueIsNotNull(string7, "RobotContext.context.getString(R.string.voice9_1)");
        String name8 = VoiceItem.voice10_2.name();
        String string8 = RobotContext.INSTANCE.getContext().getString(C5508R.string.voice10_2);
        Intrinsics.checkExpressionValueIsNotNull(string8, "RobotContext.context.getString(R.string.voice10_2)");
        String name9 = VoiceItem.voice13_1.name();
        String string9 = RobotContext.INSTANCE.getContext().getString(C5508R.string.voice13_1);
        Intrinsics.checkExpressionValueIsNotNull(string9, "RobotContext.context.getString(R.string.voice13_1)");
        String name10 = VoiceItem.voice13_2.name();
        String string10 = RobotContext.INSTANCE.getContext().getString(C5508R.string.voice13_2);
        Intrinsics.checkExpressionValueIsNotNull(string10, "RobotContext.context.getString(R.string.voice13_2)");
        String name11 = VoiceItem.voice14_1.name();
        String string11 = RobotContext.INSTANCE.getContext().getString(C5508R.string.voice14_1);
        Intrinsics.checkExpressionValueIsNotNull(string11, "RobotContext.context.getString(R.string.voice14_1)");
        String name12 = VoiceItem.voice14_2.name();
        String string12 = RobotContext.INSTANCE.getContext().getString(C5508R.string.voice14_2);
        Intrinsics.checkExpressionValueIsNotNull(string12, "RobotContext.context.getString(R.string.voice14_2)");
        String name13 = VoiceItem.voice14_3.name();
        String string13 = RobotContext.INSTANCE.getContext().getString(C5508R.string.voice14_3);
        Intrinsics.checkExpressionValueIsNotNull(string13, "RobotContext.context.getString(R.string.voice14_3)");
        String name14 = VoiceItem.voice17_1.name();
        String string14 = RobotContext.INSTANCE.getContext().getString(C5508R.string.voice17_1);
        Intrinsics.checkExpressionValueIsNotNull(string14, "RobotContext.context.getString(R.string.voice17_1)");
        String name15 = VoiceItem.voice19_1.name();
        String string15 = RobotContext.INSTANCE.getContext().getString(C5508R.string.voice19_1);
        Intrinsics.checkExpressionValueIsNotNull(string15, "RobotContext.context.getString(R.string.voice19_1)");
        String name16 = VoiceItem.voice20_1.name();
        String string16 = RobotContext.INSTANCE.getContext().getString(C5508R.string.voice20_1);
        Intrinsics.checkExpressionValueIsNotNull(string16, "RobotContext.context.getString(R.string.voice20_1)");
        String name17 = VoiceItem.voice22_1.name();
        String string17 = RobotContext.INSTANCE.getContext().getString(C5508R.string.voice22_1);
        Intrinsics.checkExpressionValueIsNotNull(string17, "RobotContext.context.getString(R.string.voice22_1)");
        String name18 = VoiceItem.voice50_1.name();
        String string18 = RobotContext.INSTANCE.getContext().getString(C5508R.string.voice50_1);
        Intrinsics.checkExpressionValueIsNotNull(string18, "RobotContext.context.getString(R.string.voice50_1)");
        String name19 = VoiceItem.voice50_2.name();
        String string19 = RobotContext.INSTANCE.getContext().getString(C5508R.string.voice50_2);
        Intrinsics.checkExpressionValueIsNotNull(string19, "RobotContext.context.getString(R.string.voice50_2)");
        String name20 = VoiceItem.voice50_3.name();
        String string20 = RobotContext.INSTANCE.getContext().getString(C5508R.string.voice50_3);
        Intrinsics.checkExpressionValueIsNotNull(string20, "RobotContext.context.getString(R.string.voice50_3)");
        String name21 = VoiceItem.voice50_4.name();
        String string21 = RobotContext.INSTANCE.getContext().getString(C5508R.string.voice50_4);
        Intrinsics.checkExpressionValueIsNotNull(string21, "RobotContext.context.getString(R.string.voice50_4)");
        String name22 = VoiceItem.voice51_1.name();
        String string22 = RobotContext.INSTANCE.getContext().getString(C5508R.string.wecome);
        Intrinsics.checkExpressionValueIsNotNull(string22, "RobotContext.context.getString(R.string.wecome)");
        String name23 = VoiceItem.voice52_1.name();
        String string23 = RobotContext.INSTANCE.getContext().getString(C5508R.string.voice52_1);
        Intrinsics.checkExpressionValueIsNotNull(string23, "RobotContext.context.getString(R.string.voice52_1)");
        String name24 = VoiceItem.voice53_1.name();
        String string24 = RobotContext.INSTANCE.getContext().getString(C5508R.string.voice53_1);
        Intrinsics.checkExpressionValueIsNotNull(string24, "RobotContext.context.getString(R.string.voice53_1)");
        String name25 = VoiceItem.voice54_1.name();
        String string25 = RobotContext.INSTANCE.getContext().getString(C5508R.string.voice54_1);
        Intrinsics.checkExpressionValueIsNotNull(string25, "RobotContext.context.getString(R.string.voice54_1)");
        String name26 = VoiceItem.voice54_2.name();
        String string26 = RobotContext.INSTANCE.getContext().getString(C5508R.string.voice54_2);
        Intrinsics.checkExpressionValueIsNotNull(string26, "RobotContext.context.getString(R.string.voice54_2)");
        String name27 = VoiceItem.voice54_3.name();
        String string27 = RobotContext.INSTANCE.getContext().getString(C5508R.string.voice54_3);
        Intrinsics.checkExpressionValueIsNotNull(string27, "RobotContext.context.getString(R.string.voice54_3)");
        String name28 = VoiceItem.voice54_4.name();
        String string28 = RobotContext.INSTANCE.getContext().getString(C5508R.string.voice54_4);
        Intrinsics.checkExpressionValueIsNotNull(string28, "RobotContext.context.getString(R.string.voice54_4)");
        String name29 = VoiceItem.voice54_5.name();
        String string29 = RobotContext.INSTANCE.getContext().getString(C5508R.string.voice54_5);
        Intrinsics.checkExpressionValueIsNotNull(string29, "RobotContext.context.getString(R.string.voice54_5)");
        String name30 = VoiceItem.voice55_1.name();
        String string30 = RobotContext.INSTANCE.getContext().getString(C5508R.string.voice55_1);
        Intrinsics.checkExpressionValueIsNotNull(string30, "RobotContext.context.getString(R.string.voice55_1)");
        return CollectionsKt.arrayListOf(new TtsVoiceItem(name, string, 0, null, null, 28, null), new TtsVoiceItem(name2, string2, 0, null, null, 28, null), new TtsVoiceItem(name3, string3, 0, null, null, 28, null), new TtsVoiceItem(name4, string4, 0, null, null, 28, null), new TtsVoiceItem(name5, string5, 0, null, null, 28, null), new TtsVoiceItem(name6, string6, 0, null, null, 28, null), new TtsVoiceItem(name7, string7, 0, null, null, 28, null), new TtsVoiceItem(name8, string8, 0, null, null, 28, null), new TtsVoiceItem(name9, string9, 0, null, null, 28, null), new TtsVoiceItem(name10, string10, 0, null, null, 28, null), new TtsVoiceItem(name11, string11, 0, null, null, 28, null), new TtsVoiceItem(name12, string12, 0, null, null, 28, null), new TtsVoiceItem(name13, string13, 0, null, null, 28, null), new TtsVoiceItem(name14, string14, 0, null, null, 28, null), new TtsVoiceItem(name15, string15, 0, null, null, 28, null), new TtsVoiceItem(name16, string16, 0, null, null, 28, null), new TtsVoiceItem(name17, string17, 0, null, null, 28, null), new TtsVoiceItem(name18, string18, 0, null, null, 28, null), new TtsVoiceItem(name19, string19, 0, null, null, 28, null), new TtsVoiceItem(name20, string20, 0, null, null, 28, null), new TtsVoiceItem(name21, string21, 0, null, null, 28, null), new TtsVoiceItem(name22, string22, 0, null, null, 28, null), new TtsVoiceItem(name23, string23, 0, null, null, 28, null), new TtsVoiceItem(name24, string24, 0, null, null, 28, null), new TtsVoiceItem(name25, string25, 0, null, null, 28, null), new TtsVoiceItem(name26, string26, 0, null, null, 28, null), new TtsVoiceItem(name27, string27, 0, null, null, 28, null), new TtsVoiceItem(name28, string28, 0, null, null, 28, null), new TtsVoiceItem(name29, string29, 0, null, null, 28, null), new TtsVoiceItem(name30, string30, 0, null, null, 28, null));
    }
}
